### ISSUE TITLE
Fetching resource AND related resources

### ISSUE THREAD

**Issue by Bazze** [traverson/traverson#88] opened 2017-02-25 15:32 UTC
Hello!

I'm trying to figure out how to get a resource AND a related resource in the best way, reading through the documentation I'm not really sure on how to achieve this. Or, rather, not sure how to achieve it without traversing from the root twice and being able to handle both a linked and embedded scenario.

Assume following endpoint and response:
```json
GET /customer/1

{
  "_links": {
    "self": {
      "href": "https://api.url/customer/1"
    },
    "curies": [
      {
        "name": "ns",
        "href": "https://api.url/rels/ns/{rel}",
        "templated": true
      }
    ],
    "ns:orders": {
      "href": "https://api.url/customer/1/orders"
    }
  },
  "name": "John Doe",
  "birthDate": "1985-02-21"
}
```

Using the code below everything is fine. I get the `customer`, then traverse to `orders` and attach it to my already fetched `customer` object. However, what happens here if the `orders` are already embedded on the customer? I use the `preferEmbeddedResources` but this doesn't really help. To fix this code in an embedded scenario where `orders` are already embedded on the `customer` I seem to need to change `.follow('ns:orders', 'ns:orders[$all]')` to `.follow('ns:orders[$all]')`.

```javascript
const getCustomerWithOrders = () => (
  new Promise((resolve, reject) => {
    traverson
      .from('https://api.url')
      .jsonHal()
      .preferEmbeddedResources()
      .follow('ns:customer')
      .withTemplateParameters({ id: 1 })
      .getResource((error, customer, traversal) => {
        if (error) {
          return reject(error);
        }

        traversal
          .continue()
          .follow('ns:orders', 'ns:orders[$all]')
          .preferEmbeddedResources()
          .getResource((error2, orders) => {
            if (error2) {
              return reject(error2);
            }

            return resolve(
              Object.assign({}, customer, { orders })
            );
          });
      });
  });
);
```

How can I support following links of a resource and prefer the embedded version in a continued traversal (using the same code)? Hopefully I'm missing something.

**Comment by Bazze** [comment] 2017-03-07 10:07
I would looove some input on this :)

**Comment by basti1302** [comment] 2017-03-24 08:52
I finally had some time to take a look at this. I must admit, I still find it quite hard to get my head around it and to understand the problem/your use case fully. If you can help me understand what you are trying to do, I might be able to help you achieve it :)

Here are some questions:

1. The service you are talking to sometimes embeds the orders in the customer and sometimes they are a linked resource, that needs to be fetched separately, is that correct?
2. In the case where orders are a linked resource, how would the resource at https://api.url/customer/1/orders look like?
3. In the embedded case, how would the customer resource look like exactly?

Maybe the resource design can be improved to handle both cases with the same code, maybe traverson or traverson-hal needs additional features to solve this use case - I honestly don't know yet.

**Comment by Bazze** [comment] 2017-03-24 09:27
Thanks @basti1302. I actually think you understood perfectly what I meant based on your bullet points.

1. The service you are talking to sometimes embeds the orders in the customer and sometimes they are a linked resource, that needs to be fetched separately, is that correct?
**Yes, that is correct.**
2. In the case where orders are a linked resource, how would the resource at https://api.url/customer/1/orders look like?
**It would be an object, with an `_embedded` prop which has an `orders` props which is an array of orders. See Example 1 below.**
3. In the embedded case, how would the customer resource look like exactly?
**It would have the embedded orders attached directly to the customer resource. See Example 2 below.**

**Example 1**
```javascript
// GET /customers/1/orders

{
 [...]
 "_embedded": {
    "ns:orders": [
      {}, {}, {}
    ]
  }
}
```

**Example 2**
```javascript
// GET /customers/1 (with default embedded orders)

{
  "_links": {
    "self": {
      "href": "https://api.url/customer/1"
    },
    "ns:orders": {
      "href": "https://api.url/customer/1/orders"
    }
  },
  "name": "John Doe",
  "birthDate": "1985-02-21",
  "_embedded": {
    "ns:orders": [
      {}, {}, {}
    ]
  }
}
```

**Comment by basti1302** [comment] 2017-03-24 11:31
From my perspective, the root problem is that the path to the resources is indeed different for both cases. The full path, starting at `/customer/1` is 
* for the embedded case: `"ns:orders"`
* for the non-embedded case: `"ns:orders", "ns:orders"`.

That is between the resource reached by following the link resource `ns:orders` has another embedded `"ns:orders"` inside. 

The [spec suggests](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-8.3) that "servers add an embedded resource into the representation with the same relation. Following that thought, your embedded orders should be the same thing as the linked resource - but they are not the same thing in your example. The embedded orders are a an array, the linked orders are a object that contains an embedded array. This is the mismatch. There is no way to gloss over this mismatch with Traverson/traverson-hal right now. I'm not sure if there should be one.

However, the spec is also confusing (at least for me) in this regard, because [this example document](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-6) does also not follow this pattern.

I would have suggested to change the orders resource so that it matches your embedded array, but HAL resources always need to be objects, not arrays, so this is not possible.

Do you have control over the server's resource structure? How about this resource structure: 

```
GET /customer/1
{
  "_links": {
    "self": { 
      "href": "https://api.url/customer/1"
    },
    "ns:order-list": {
      "href": "https://api.url/customer/1/order-list"
    }
  },
  "_embedded": {
     "ns:order-list": {
       "orders": [{...}, {...}, {...}]
     }
   }
  "name": "John Doe",
  "birthDate": "1985-02-21"
}

// GET /customers/1/order-list
{
  "_links": {
    "self": "href": "https://api.url/customer/1/order-list"
  },
  "orders": [{...}, {...}, {...}]
}
```

Then the embedded resource and the linked resource would actually be the same thing. Not sure if this is a better (or even a good) resource design, though.


Another possibility (that would not work currently, see below) is to use the following Traverson code:

``` 
traverson
      .from('https://api.url')
      .jsonHal()
      .preferEmbeddedResources()
      .follow('ns:customer')) 
      .withTemplateParameters({ id: 1 })
      .getResource((error, customer, traversal) => {
        if (error) {
          return reject(error);
        }

        traversal
          .continue()
          .follow('ns:orders[$all]')  // directly ask for the embedded orders, if they are present
          .preferEmbeddedResources()
          .getResource((error2, orders) => {
            if (error2) {
              return reject(error2);
            }

            // Now examine what you received, either the array of embedded resources or a resource that 
            // contains another embedded array. In the latter case you need to peel the actual array out of
            // out of the resource but you should not need another http request.
            ...
          });
      });
``` 

The problem is, when a link relation uses `ns:orders[$all]`, traverson-hal currently does not even try to find a link relation `ns:orders` but only looks for an embedded array. Theoretically, this could be changed so that the `[$all]` meta-selector is ignored when there is no embedded array but a link relation that matches. However, I'm not sure if this would be a good design decision for traverson-hal.

**Comment by basti1302** [comment] 2017-04-05 10:40
Closing this for now. Feel free to reopen or open a new feature request if you have more thoughts on that.

**Closed by basti1302** 2017-04-05 10:40 UTC
