### ISSUE TITLE
.from() does not return unique instance

### ISSUE THREAD

**Issue by primavera133** [traverson/traverson#101] opened 2017-10-09 13:50 UTC
According to the documentation: "from(url): Returns a new request builder instance with the given root URL. Thus, traverson.from(url) is equivalent to newRequest().from(url)`."

Well, it seems we encountered a case where it did not do this and we had race-conditions and messed up API-calls.

What we did was first to store the following code in an instance:
```
const api = traverson
	.from(config.get('imh.rootUrl'))
	.json()
	.withRequestOptions({
		'headers': {
			'Content-Type': 'application/json; charset=utf-8'
		},
		'strictSSL': false,
		'auth': {
			'user': config.get('apiKey'),
			'pass': config.get('password')
		}
	})
	.convertResponseToObject();
```

Then when instancing a HapiJS model Class we ran the .from() again in the constructor, like this: 
```	
constructor (url) {
		this.url = url;
		this.api = api.from(url);
	}
```

The idea behind this was to store a given URL on the encounter-object in our database to reuse for all communication with the external API. A shortcut in communicating with our external API. Only problem it turned out the second .from()-method didn't return a unique instance! 

We found it could be fixed in two ways:
A) in the constructor, call newRequest() : `this.api = api.newRequest().from(url)`
B) Refactor the first constant to a function that returns the object. Which would be called like: `this.api = api().from(url)`

We went with the second solution, deploying a hotfix to production tomorrow and hope to never see any mixed up encounters again after that.

**Comment by basti1302** [comment] 2017-10-09 21:39
Indeed, `traverson.from(url)` is equivalent to `traverson.newRequest().from(url)`, as stated in the docs. This section talks about calling the `from` method on the traverson object (the object acquired by `var traverson = require('traverson')`). This is clearly stated in the docs.

You, however are calling the `from` method on the request builder (which you named `api`, that is, the object returned by `traverson.from()`. The docs do not claim that this is a new instance. Here's what the docs say about this method:

> `from(url)`: Set the root URL of the API, that is, where the link traversal begins. If you created the request builder instance with traverson.from(url) you don't need to call from on the request builder instance. This method returns the request builder instance to allow for method chaining.

If you have suggestions on how to improve the docs to be clearer on this point, I'd be open for them.

Closing for now, as this behaves as designed.

**Closed by basti1302** 2017-10-09 21:39 UTC

**Comment by basti1302** [comment] 2017-10-09 21:43
FYI, I would have used 		

```
this.url = url;
this.api = api.newRequest().from(url);
```

in the constructor of you Hapi model to solve this - that's what the newRequest method is intended for. YMMV.

**Comment by primavera133** [comment] 2017-10-10 07:13
Thanks for pointing this out, and for the recommendation for solving our issue. Much appreciated.
